-- 0025_campaign_report_exports
-- Asynchronous, tenant-scoped campaign report exports. The queue is
-- contentless so a worker may discover a tenant before entering its RLS
-- context; every report parameter and every generated byte remains in the
-- FORCE-RLS table.

CREATE TABLE campaign_report_exports (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  tenant_id uuid NOT NULL,
  requested_by_membership_id uuid NOT NULL,
  campaign_id uuid,
  format text NOT NULL CHECK (format IN ('csv')),
  state text NOT NULL DEFAULT 'queued'
    CHECK (state IN ('queued','running','completed','failed')),
  attempt integer NOT NULL DEFAULT 0 CHECK (attempt >= 0 AND attempt <= 3),
  lease_owner text,
  lease_expires_at timestamptz,
  row_count integer CHECK (row_count IS NULL OR row_count >= 0),
  content_text text,
  content_sha256 text CHECK (content_sha256 IS NULL OR content_sha256 ~ '^[0-9a-f]{64}$'),
  error_code text,
  requested_at timestamptz NOT NULL DEFAULT now(),
  started_at timestamptz,
  completed_at timestamptz,
  expires_at timestamptz,
  CONSTRAINT campaign_report_exports_tenant_id_uq UNIQUE (tenant_id,id),
  CONSTRAINT campaign_report_exports_requester_fk
    FOREIGN KEY (tenant_id,requested_by_membership_id)
    REFERENCES memberships(tenant_id,id),
  CONSTRAINT campaign_report_exports_campaign_fk
    FOREIGN KEY (tenant_id,campaign_id)
    REFERENCES campaigns(tenant_id,id),
  CONSTRAINT campaign_report_exports_shape_ck CHECK (
    (state='queued' AND attempt=0 AND lease_owner IS NULL AND lease_expires_at IS NULL
      AND row_count IS NULL AND content_text IS NULL AND content_sha256 IS NULL
      AND error_code IS NULL AND started_at IS NULL AND completed_at IS NULL AND expires_at IS NULL)
    OR
    (state='running' AND attempt BETWEEN 1 AND 3 AND lease_owner IS NOT NULL
      AND lease_expires_at IS NOT NULL AND started_at IS NOT NULL
      AND row_count IS NULL AND content_text IS NULL AND content_sha256 IS NULL
      AND error_code IS NULL AND completed_at IS NULL AND expires_at IS NULL)
    OR
    (state='completed' AND attempt BETWEEN 1 AND 3 AND lease_owner IS NULL
      AND lease_expires_at IS NULL AND row_count IS NOT NULL AND content_text IS NOT NULL
      AND content_sha256 IS NOT NULL AND error_code IS NULL AND started_at IS NOT NULL
      AND completed_at IS NOT NULL AND expires_at > completed_at)
    OR
    (state='failed' AND attempt BETWEEN 1 AND 3 AND lease_owner IS NULL
      AND lease_expires_at IS NULL AND row_count IS NULL AND content_text IS NULL
      AND content_sha256 IS NULL AND error_code IS NOT NULL AND started_at IS NOT NULL
      AND completed_at IS NOT NULL AND expires_at IS NULL)
  )
);

CREATE TABLE campaign_report_export_queue (
  export_id uuid PRIMARY KEY,
  tenant_id uuid NOT NULL,
  available_at timestamptz NOT NULL DEFAULT now(),
  created_at timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT campaign_report_export_queue_export_fk FOREIGN KEY (tenant_id,export_id)
    REFERENCES campaign_report_exports(tenant_id,id) ON DELETE CASCADE
);

CREATE INDEX campaign_report_export_queue_due_idx
  ON campaign_report_export_queue(available_at,tenant_id,export_id);

ALTER TABLE campaign_report_exports ENABLE ROW LEVEL SECURITY;
ALTER TABLE campaign_report_exports FORCE ROW LEVEL SECURITY;
CREATE POLICY tenant_isolation ON campaign_report_exports
  USING (tenant_id=app_current_tenant()) WITH CHECK (tenant_id=app_current_tenant());

GRANT SELECT,INSERT,UPDATE ON campaign_report_exports TO convo_app;
-- No report content or filter is stored here. Discovery reveals only that a
-- tenant has work, after which the worker enters the tenant transaction.
GRANT SELECT,INSERT,UPDATE,DELETE ON campaign_report_export_queue TO convo_app;
